# Generated by Django 6.0.2 on 2026-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address of the card owner (for unauthenticated users)', max_length=254)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('digit', models.CharField(max_length=19)),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover'), ('other', 'Other')], default='other', max_length=50)),
                ('exp_month', models.PositiveSmallIntegerField()),
                ('exp_year', models.PositiveSmallIntegerField()),
                ('cvv', models.CharField(max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('billing_address_line1', models.CharField(max_length=255)),
                ('billing_address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('billing_city', models.CharField(max_length=100)),
                ('billing_state', models.CharField(max_length=100)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('billing_country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
